# Generated by Django 2.1.13 on 2019-11-01 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoX509Ca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('notes', models.TextField()),
                ('key_length', models.CharField(max_length=6)),
                ('digest', models.CharField(max_length=8)),
                ('validity_start', models.DateTimeField(blank=True, null=True)),
                ('validity_end', models.DateTimeField(blank=True, null=True)),
                ('country_code', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('organization_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=254)),
                ('common_name', models.CharField(max_length=63)),
                ('extensions', models.TextField()),
                ('serial_number', models.CharField(blank=True, max_length=39, null=True)),
                ('certificate', models.TextField()),
                ('private_key', models.TextField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('organizational_unit_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'django_x509_ca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoX509Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('notes', models.TextField()),
                ('key_length', models.CharField(max_length=6)),
                ('digest', models.CharField(max_length=8)),
                ('validity_start', models.DateTimeField(blank=True, null=True)),
                ('validity_end', models.DateTimeField(blank=True, null=True)),
                ('country_code', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('organization_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=254)),
                ('common_name', models.CharField(max_length=63)),
                ('extensions', models.TextField()),
                ('serial_number', models.CharField(blank=True, max_length=39, null=True)),
                ('certificate', models.TextField()),
                ('private_key', models.TextField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('revoked', models.IntegerField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('organizational_unit_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'django_x509_cert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mainkey',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('key_name', models.TextField()),
                ('time_start', models.TimeField()),
            ],
            options={
                'db_table': 'mainkey',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrator'), (2, 'Country Signing Certification Authority'), (3, 'Document Signer'), (4, 'Inspection System'), (5, 'Master List Signer'), (6, 'Document List Signer')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
