# Generated by Django 2.1.13 on 2019-10-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
