# Generated by Django 2.1.13 on 2019-11-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairKeyReq',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('masterkey', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('jalan', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
            ],
        ),
    ]
