# Generated by Django 2.1.13 on 2019-10-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterKey',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=70)),
                ('kunci', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'masterkey',
                'managed': False,
            },
        ),
    ]
