# Generated by Django 2.1.13 on 2019-10-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0002_masterkey'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterkey',
            table='master',
        ),
    ]
