# Generated by Django 2.1.13 on 2019-10-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainkey',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('kunci', models.TextField()),
            ],
            options={
                'db_table': 'mainkey',
                'managed': False,
            },
        ),
    ]
