# Generated by Django 2.1.13 on 2019-11-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0002_pairkeyreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairkeyreq',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
