# Generated by Django 2.1.13 on 2019-11-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0003_pairkeyreq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairkeyreq',
            name='sbit',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
