# Generated by Django 2.1.13 on 2019-10-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0004_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterkey',
            options={},
        ),
    ]
