# Generated by Django 2.1.13 on 2019-11-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0004_pairkeyreq_sbit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairkeyreq',
            old_name='sbit',
            new_name='bit',
        ),
    ]
