# Generated by Django 2.1.13 on 2019-11-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0005_auto_20191105_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairkeyreq',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
