# Generated by Django 2.1.13 on 2019-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0005_auto_20191024_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkey',
            name='id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='masterkey',
            name='kunci',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='masterkey',
            table=None,
        ),
    ]
