# Generated by Django 2.1.13 on 2019-11-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0006_pairkeyreq_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairkeyreq',
            name='jenis',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
