# Generated by Django 2.1.13 on 2019-10-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0007_auto_20191024_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterkey1',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('kunci', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MasterKey',
        ),
    ]
