# Generated by Django 2.1.13 on 2019-11-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0007_pairkeyreq_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairkeyreq',
            name='privkey',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pairkeyreq',
            name='pubkey',
            field=models.TextField(null=True),
        ),
    ]
