# Generated by Django 2.1.13 on 2019-10-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0008_auto_20191024_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='masterkey1',
            new_name='masterkey',
        ),
    ]
