# Generated by Django 2.1.13 on 2019-10-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0009_auto_20191024_1416'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterkey',
            table='master',
        ),
    ]
