# Generated by Django 2.1.13 on 2019-10-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0010_auto_20191024_1437'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterkey',
            table='masterkey',
        ),
    ]
