# Generated by Django 2.1.13 on 2019-10-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0011_auto_20191024_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='kuncii',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('kunci', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kuncii',
            },
        ),
    ]
